/*CRIANDO BANCO*/
CREATE DATABASE DADOS_DE_CLIENTES;

/*USANDO BANCO*/
USE DADOS_DE_CLIENTES;

/*CRIANDO TABELA CLIENTE*/
CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
SEXO ENUM ('M', 'F'),
EMAIL VARCHAR (50),
CPF VARCHAR (14)
);

INSERT INTO CLIENTE VALUES (NULL, 'Guilherme da Silva Pessoa Lucas', 'M', 'forcecell954@gmail.com', '00000000001');
INSERT INTO CLIENTE VALUES (NULL, 'Luiz Faria Santos', 'M', 'luizfaria@gmail.com', '00000000002');
INSERT INTO CLIENTE VALUES (NULL, 'Agatha Thainá da Silva', 'F', 'Agathasilva@gmail.com', '00000000003');






/*CRIANDO TABELA ENDERECO*/
CREATE TABLE ENDERECO (
IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR (50) NOT NULL,
BAIRRO VARCHAR (25) NOT NULL,
CIDADE VARCHAR (25) NOT NULL,
N_CASA VARCHAR (5) NOT NULL, 
ESTADO CHAR (2) NOT NULL
);


INSERT INTO ENDERECO VALUES (NULL, 'Rua padre josé ribeiro', 'Jardim Tupã', 'Barueri', '125', 'SP');
INSERT INTO ENDERECO VALUES (NULL, 'Jacarai Perreira', 'Jardim do Edem', 'Franca', '13', 'SP');
INSERT INTO ENDERECO VALUES (NULL, 'Avenida São Paulo', 'Aristn 1', 'Carapicuiba', '233', 'SP');










/* CRIANDO TABELA TELEFONE */
CREATE TABLE TELEFONE (
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM ('CEL', 'RES', 'COM'),
NUMERO CHAR (13)
);

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '5511000000001');
INSERT INTO TELEFONE VALUES (NULL, 'RES', '5511000000002');
INSERT INTO TELEFONE VALUES (NULL, 'COM', '5511000000003');






/* SELECIONANDO AS 3 TABELAS POR ID */
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, N_CASA, TIPO, NUMERO
FROM CLIENTE 
INNER JOIN ENDERECO
ON IDCLIENTE = IDENDERECO
INNER JOIN TELEFONE 
ON IDTELEFONE = IDENDERECO;



/* SELECIONAR POR ID */
SELECT IDCLIENTE, NOME, SEXO, EMAIL, CPF, RUA, BAIRRO, CIDADE, ESTADO, N_CASA, TIPO, NUMERO
FROM CLIENTE 
INNER JOIN ENDERECO
ON IDCLIENTE = IDENDERECO
INNER JOIN TELEFONE 
ON IDTELEFONE = IDENDERECO 
WHERE IDCLIENTE = 1;


/* ATUALIZAR CAMPO BAIRRO */
UPDATE ENDERECO
SET BAIRRO = 'Jardim do Edem'
WHERE IDENDERECO=2;


/* ATUALIZANDO MAIS DE UMA LINHA AO MESMO TEMPO */
UPDATE ENDERECO
SET BAIRRO = 'Ariston 2'
WHERE IDENDERECO IN (1,2,3);



/* QUANTIDADE DE PESSOAS DE CADA SEXO */
SELECT COUNT(*) AS QUANTIDADE_POR_SEXO, SEXO
FROM CLIENTE
GROUP BY SEXO;
